### ISSUE TITLE
Data set download problem

### ISSUE THREAD

**Issue by 3091578729** [computational-imaging/nlos-fk#1]
I came across your paper "Wave-Based Non-Line-of-Sight Imaging using Fast f-k Migration" which I found very insightful. I have been trying to replicate some of your methods, but have run into some issues during the modeling process. Specifically, I have been unable to download the full dataset which is stored on Google Drive. Despite trying various methods, the download always disconnects before completion. The download link for the Google Drive dataset is: https://drive.google.com/file/d/1_av9TdJ-J22qAUNs1ueZ8ETuRRW2KHg_/view
The dataset is very important to my research and I am hoping to be able to successfully download it.
Thank you very much for your time and assistance.

**Comment by davelindell** [comment]
Please try downloading the files individually from our [project webpage](http://www.computationalimaging.org/publications/nlos-fk/). These will have smaller file sizes, and hopefully you're less likely to get disconnected.

**Comment by 3091578729** [comment]
Thank you very very very much,Professor David Lindell. My problem has been resolved. I wish you all the best in your future academic achievements.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "computational-imaging/nlos-fk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 凌晨4:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [computational-imaging/nlos-fk] Data set download problem (Issue #1)





 
Closed #1 as completed.
